# Generated by Django 5.0.2 on 2024-02-16 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_reservation_is_conformed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number must be format '+380xxxxxxxxx'. Up to 15 digits", regex='^\\+?380\\d{9}$')]),
        ),
    ]
